name: team3
channels:
  - conda-forge
  - defaults
dependencies:
  - autoflake
  - autopep8
  - dlib
  - libflac
  - opencv
  - paho-mqtt
  - pip
  - py-opencv
  - pylint
  - python
  - python-socketio
  - requests
  - websocket-client
  - pip:
    - pyaudio
    - pygame
    - pygame-gui
    - pyttsx3
    - speechrecognition==3.8.1
