name: autopep8
on: push
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --pep8-passes 2000 --verbose --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name '[BOT] Will'
          git config --global user.email 'randallwc@users.noreply.github.com'
          git commit -am "Automated autopep8 fixes"
          git push
